VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISpaceObject"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Let left(ByRef changeLeft As Long)
End Property

Public Property Get left() As Long
End Property

Public Property Let top(ByRef changeTop As Long)
End Property

Public Property Get top() As Long
End Property

Public Property Get width() As Long
End Property

Public Property Get height() As Long
End Property

Public Property Get ImageName() As String
End Property

Public Property Get ImagePathway() As String
End Property


